project:
  type: book

book:
  title: "Data Magic"
  author: "Leanne Coetzee & Steve Markham"
  date: today
  date-format: "D MMMM YYYY"
  chapters:
    - index.qmd
    - intro.qmd
    - database.qmd
    - transformation.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    fontsize: 1.1em
    linestretch: 1.5
    code-fold: true
    code-summary: "Show the code"
  pdf:
    documentclass: scrreprt



