project:
  type: book

book:
  title: "Data Magic"
  author: "Leanne Coetzee & Steve Markham"
  date: "08/25/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - database.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



